name       : python-simplejson
version    : 3.10.0
release    : 3
source     :
    - https://github.com/simplejson/simplejson/archive/v3.10.0.tar.gz : 7a9d120308a21b062e5fb53268da7cd335e24351200a80d7b2162d264252327f
license    :
    - AFL-2.1
    - MIT
component  : programming.python
summary    : simplejson is a simple, fast, extensible JSON encoder/decoder for Python
description: |
    simplejson is a simple, fast, extensible JSON encoder/decoder for Python
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
