name       : python-simplejson
version    : 3.7.3
release    : 2
source     :
    - https://github.com/simplejson/simplejson/archive/v3.7.3.tar.gz : f3984a2df9eb186fa871caf4e131fad64154d5e67c296bb29f32f854afcf0689
license    :
    - AFL-2.1
    - MIT
summary    : simplejson is a simple, fast, extensible JSON encoder/decoder for Python
description: |
    simplejson is a simple, fast, extensible JSON encoder/decoder for Python
builddeps  :
setup      : |
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
