name       : python-simplejson
version    : 3.14.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/s/simplejson/simplejson-3.14.0.tar.gz : 1ebbd84c2d7512f7ba65df0b9cc3cbc1bbd6ef9eab39fc9389dfe7e3681f7bd2
license    : MIT
component  : programming.python
summary    : simplejson is a simple, fast, extensible JSON encoder/decoder for Python
description: |
    simplejson is a simple, fast, complete, correct and extensible JSON encoder and decoder for Python. It is pure Python code with no dependencies, but includes an optional C extension for a serious speed boost.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
