name       : python-simplejson
version    : 3.16.1
release    : 9
source     :
    - https://github.com/simplejson/simplejson/releases/download/v3.16.1/simplejson-3.16.1.tar.gz : 20c626174a3cfcc69c783930ac2d5daa72787a8e26398e33c978065a51cc8bf4
license    : MIT
component  : programming.python
summary    : simplejson is a simple, fast, extensible JSON encoder/decoder for Python
description: |
    simplejson is a simple, fast, complete, correct and extensible JSON encoder and decoder for Python. It is pure Python code with no dependencies, but includes an optional C extension for a serious speed boost.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3
